server:
  port: 8980

spring:
  application:
    name: API-ADMINS
  cloud:
    nacos:
      discovery:
        server-addr: 8.136.187.29:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yingxue?characterEncoding=UTF-8&useSSL=false
    username: root
    password: zxh228..
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
  #    host: 8.136.187.29
  #    port: 6379
  jackson:
    default-property-inclusion: non_null
  mvc:
    hiddenmethod:
      filter:
        enabled: true
mybatis:
  mapper-locations: classpath:com/zhangxuhui/mapper/*.xml
  type-aliases-package: com.zhangxuhui.entity

logging:
  level:
    com.zhangxuhui.dao: debug
