server:
  port: 8981

spring:
  application:
    name: API-CATEGORYS
  cloud:
    nacos:
      discovery:
        server-addr: 8.136.187.29:8848

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yingxue?characterEncoding=UTF-8&useSSL=false
    username: root
    password: zxh228..
  jackson:
    default-property-inclusion: non_null
mybatis:
  mapper-locations: classpath:com/zhangxuhui/mapper/*.xml
  type-aliases-package: com.zhangxuhui.entity
logging:
  level:
    com.zhangxuhui.mapper: debug

