server:
  port: 8982
spring:
  application:
    name: API-USERS
  cloud:
    nacos:
      discovery:
        server-addr: 8.136.187.29:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.136.187.29:3306/yingxue?characterEncoding=UTF-8&useSSL=false
    username: root
    password: zxh228..
    jackson:
      default-property-inclusion: non_null
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhangxuhui.entity
logging:
  level:
    com.zhangxuhui.mapper: debug
